// ⚠️  AUTO-GENERATED — do not edit by hand.
// Source of truth: eerie-rpc/src/lib.rs  (roam service trait)
// Regenerate with: pnpm codegen
//
// Transport: TCP (roam-stream on Rust side, @bearcove/roam-tcp on TS side).

// @generated by roam-codegen
// DO NOT EDIT - regenerate with `cargo xtask codegen --typescript`

import type { Caller, MethodDescriptor, ServiceDescriptor, RoamCall, ChannelingDispatcher } from "@bearcove/roam-core";
import { CallBuilder, helloExchangeInitiator, defaultHello } from "@bearcove/roam-core";
import { connectWs } from "@bearcove/roam-ws";

// Request/Response type aliases
export type PingRequest = [];
export type PingResponse = string;

// Caller interface for EerieDaemon
export interface EerieDaemonCaller {
  ping(): CallBuilder<string>;
}

// Client implementation for EerieDaemon
export class EerieDaemonClient implements EerieDaemonCaller {
  private caller: Caller;

  constructor(caller: Caller) {
    this.caller = caller;
  }

  ping(): CallBuilder<string> {
    const descriptor = eerieDaemon_descriptor.methods[0];
    return new CallBuilder(async (metadata) => {
      const value = await this.caller.call({
        method: "EerieDaemon.ping",
        args: {},
        descriptor,
        metadata,
      });
      return value as string;
    });
  }

}

/**
 * Connect to a EerieDaemon server over WebSocket.
 * @param url - WebSocket URL (e.g., "ws://localhost:9000")
 * @returns A connected EerieDaemonClient instance
 */
export async function connectEerieDaemon(url: string): Promise<EerieDaemonClient> {
  const transport = await connectWs(url);
  const connection = await helloExchangeInitiator(transport, defaultHello());
  return new EerieDaemonClient(connection.asCaller());
}

// Handler interface for EerieDaemon
export interface EerieDaemonHandler {
  ping(): Promise<string> | string;
}

// Dispatcher for EerieDaemon
export class EerieDaemonDispatcher implements ChannelingDispatcher {
  constructor(private readonly handler: EerieDaemonHandler) {}

  getDescriptor(): ServiceDescriptor {
    return eerieDaemon_descriptor;
  }

  async dispatch(method: MethodDescriptor, args: unknown[], call: RoamCall): Promise<void> {
    if (method.id === 0x8ae8d551829a3269n) {
      try {
        const result = await this.handler.ping();
        call.reply(result);
      } catch {
        call.replyInternalError();
      }
    }
  }
}

// Service descriptor for runtime schema-driven dispatch
export const eerieDaemon_descriptor: ServiceDescriptor = {
  service_name: 'EerieDaemon',
  methods: [
    {
      name: 'ping',
      id: 0x8ae8d551829a3269n,
      args: { kind: 'tuple', elements: [] },
      result: { kind: 'enum', variants: [{ name: 'Ok', fields: { kind: 'string' } }, { name: 'Err', fields: { kind: 'enum', variants: [{ name: 'User', fields: null }, { name: 'UnknownMethod', fields: null }, { name: 'InvalidPayload', fields: null }, { name: 'Cancelled', fields: null }] } }] },
    },
  ],
};

